config/routes.rb
ProjetoSemNome::Application.routes.draw do
  root to: 'welcome#index'

  #routes for the ability module
  get '/abilities' => 'abilities#index', as: 'abilities'
  get '/abilities/new' => 'abilities#new', as: 'new_ability'
  get '/abilities/edit/:id' => 'abilities#edit', as: 'edit_ability'
  get '/abilities/show/:id' => 'abilities#show', as: 'show_ability'
  post '/abilities/create' => 'abilities#create', as: 'create_ability'
  post '/abilities/update/:id' => 'abilities#update', as: 'update_ability'
  get '/abilities/destroy/:id' => 'abilities#destroy', as: 'destroy_ability'

  #routes for the function module
  get '/functions' => 'functions#index', as: 'functions'
  get '/functions/new' => 'functions#new', as: 'new_function'
  get '/functions/edit/:id' => 'functions#edit', as: 'edit_function'
  get '/functions/show/:id' => 'functions#show', as: 'show_function'
  post '/functions/create' => 'functions#create', as: 'create_function'
  post '/functions/update/:id' => 'functions#update', as: 'update_function'
  get '/functions/destroy/:id' => 'functions#destroy', as: 'destroy_function'

 #routes for module_languages
 get'/languages' => 'languages#index', as: 'languages'
 get '/language/new' => 'languages#new', as: 'new_language'
 post '/language/create' => 'languages#create', as: 'create_language'
 get '/language/edit/:id' => 'languages#edit', as: 'edit_language'
 get '/language/destroy/:id' => 'languages#destroy', as: 'destroy_language'
 get '/language/show/:id' => 'languages#show', as: 'show_language'
 post '/language/update/:id' => 'languages#update', as: 'update_language'

 get '/projects' => 'projects#index', as:'projects'
 get '/project/new' => 'projects#new', as: 'new_project'
 post '/project/create' => 'projects#create', as: 'create_project'
 get '/project/edit/:id' => 'projects#edit', as: 'edit_project'
 get '/project/destroy/:id' => 'projects#destroy', as:'destroy_project'
 get '/project/show/:id' => 'projects#show', as: 'show_project'
 post '/project/update/:id' => 'projects#update', as: 'update_project'

 #routes for module_local
 get'/places' => 'places#index', as: 'places'
 get '/places/new' => 'places#new', as: 'new_local'
 post'/places/create' => 'places#create', as: 'create_local'
 get'/places/edit/:id' => 'places#edit', as: 'edit_local'
 get'/places/destroy/:id' => 'places#destroy', as: 'destroy_local'
 get'/places/show/:id' => 'places#show', as: 'show_local'
 post'/places/update/:id' => 'places#update', as: 'update_local'

 #errors routes
 get '/notfound' => 'errors#404', as: 'notfound'

 #sessions routes
 post '/sessions/start' => 'sessions#start_session', as: 'start_session'
 get '/sessions/end' => 'sessions#end_session', as: 'end_session'

 #dashboard routes
 get '/dashboard' => 'dashboard#index', as: 'dashboard'

 #users routes
 get '/users' => 'users#index', as: 'users'
 get '/user/new' => 'users#new', as: 'new_user'
 get '/user/edit/:id' => 'users#edit', as: 'edit_user'
 get '/user/show/:id' => 'users#show', as: 'show_user'
 post '/user/create' => 'users#create', as: 'create_user'
 post '/user/update/:id' => 'users#update', as: 'update_user'
 get '/user/destroy/:id' => 'users#destroy', as: 'destroy_user'
 get '/user/profile/edit' => 'users#edit_profile', as: 'edit_profile_user'
 post '/user/profile/update' => 'users#update_profile', as: 'update_profile_user'
 get '/user/password/change' => 'users#change_password', as: 'change_password_user'
 post '/user/password/update' => 'users#update_password', as: 'update_password_user'

end

app/models/function.rb
class Function < ActiveRecord::Base
  attr_accessible :name,
                  :function_user_projects_attributes,
                  :users_attributes,
                  :projects_attributes
                  validates :name, presence: true,
                  uniqueness: {case_sensintive: false}

  has_many :function_user_projects, :dependent => :destroy
  has_many :users, through: :function_user_projects
  has_many :projects, through: :function_user_projects
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
	def index
		@functions = Function.all
	end

	def new
		@function = Function.new
		@path_to_save = create_function_path
	end

	def edit
		@function = Function.find(params[:id])
		@path_to_save = update_function_path(params[:id])
	end

	def show
		@function = Function.find(params[:id])
	end

	def create
		@function = Function.new(params[:function])

		if @function.save
			redirect_to functions_path
		else
			@path_to_save = create_function_path
			render :new
		end
	end

	def update
		@function = Function.find(params[:id])

		if @function.update_attributes(params[:function])
			redirect_to functions_path
		else
			@path_to_save = update_function_path(params[:id])
			render :edit
		end
	end


	def destroy
		function = Function.find(params[:id])
		function.destroy
	rescue
	ensure
		redirect_to functions_path
	end
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/functions/_form.html.erb
<div class="container">
	<div class="col-md-6">	
		<%= form_for @function, url: @path_to_save, method: 'post', html: {id: 'form-ability'} do |f| %>
			<div class="form-group">
				<%= f.label :nome %>
				<%= f.text_field :name, class: 'form-control' %>
			</div>
		
			<div>
		  		<%= f.submit 'Salvar', class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

<script type="text/javascript">
	// $("#salvar").click(function(){
	// 	$("#form-ability").submit();
	// });
</script>

app/views/functions/edit.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Funçao: Editando</a>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Cancelar', functions_path %></li>
    </ul>
  </div>
</nav>

<%= render 'form' %>

app/views/functions/index.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Funçoes</a>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
    	<li><%= link_to 'Novo', new_function_path %></li>
    </ul>
  </div>
</nav>

<table class="table table-hover table-bordered">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Açoes</th>
		</tr>
	</thead>
	<tbody>
		<% @functions.each do |function| %>
		<tr>
			<td><%= function.name %></td>
			<td>
				<%= link_to edit_function_path(function.id), title: 'Editar' do  %>
          			<span class="glyphicon glyphicon-pencil"></span>
        		<% end %>
        		<%= link_to show_function_path(function.id), title: 'Exibir' do  %>
	          		<span class="glyphicon glyphicon-eye-open"></span>
    		    <% end %>
        		<%= link_to destroy_function_path(function.id), title: 'Excluir' do %>
          			<span class="glyphicon glyphicon-trash"></span>
        		<% end %>
      		</td>
    	</tr>
    	<% end %>
  	</tbody>
</table>

app/views/functions/new.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Nova Funçao</a>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Cancelar', functions_path %></li>
    </ul>
  </div>
</nav>

<%= render 'form' %>

app/views/functions/show.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Funçoes: Exibindo</a>
  </div>
 

 <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
    	<li><%= link_to 'Cancelar', functions_path %></li>
    </ul>
  </div>
</nav>

<div class="container">
	<div class="panel panel-default">
	  <div class="panel-heading">
			<h3 class="panel-title">Nome</h3>
	  </div>
	  <div class="panel-body">
		<p><%= @function.name %></p>
	  </div>
	</div>
</div>