config/routes.rb
ProjetoSemNome::Application.routes.draw do
  root to: 'welcome#index'

  #routes for the ability module
  get '/abilities' => 'abilities#index', as: 'abilities'
  get '/abilities/new' => 'abilities#new', as: 'new_ability'
  get '/abilities/edit/:id' => 'abilities#edit', as: 'edit_ability'
  get '/abilities/show/:id' => 'abilities#show', as: 'show_ability'
  post '/abilities/create' => 'abilities#create', as: 'create_ability'
  post '/abilities/update/:id' => 'abilities#update', as: 'update_ability'
  get '/abilities/destroy/:id' => 'abilities#destroy', as: 'destroy_ability'

  #routes for the function module
  get '/functions' => 'functions#index', as: 'functions'
  get '/functions/new' => 'functions#new', as: 'new_function'
  get '/functions/edit/:id' => 'functions#edit', as: 'edit_function'
  get '/functions/show/:id' => 'functions#show', as: 'show_function'
  post '/functions/create' => 'functions#create', as: 'create_function'
  post '/functions/update/:id' => 'functions#update', as: 'update_function'
  get '/functions/destroy/:id' => 'functions#destroy', as: 'destroy_function'

 #routes for module_languages
 get'/languages' => 'languages#index', as: 'languages'
 get '/language/new' => 'languages#new', as: 'new_language'
 post '/language/create' => 'languages#create', as: 'create_language'
 get '/language/edit/:id' => 'languages#edit', as: 'edit_language'
 get '/language/destroy/:id' => 'languages#destroy', as: 'destroy_language'
 get '/language/show/:id' => 'languages#show', as: 'show_language'
 post '/language/update/:id' => 'languages#update', as: 'update_language'

 get '/projects' => 'projects#index', as:'projects'
 get '/project/new' => 'projects#new', as: 'new_project'
 post '/project/create' => 'projects#create', as: 'create_project'
 get '/project/edit/:id' => 'projects#edit', as: 'edit_project'
 get '/project/destroy/:id' => 'projects#destroy', as:'destroy_project'
 get '/project/show/:id' => 'projects#show', as: 'show_project'
 post '/project/update/:id' => 'projects#update', as: 'update_project'

 #routes for module_local
 get'/places' => 'places#index', as: 'places'
 get '/places/new' => 'places#new', as: 'new_local'
 post'/places/create' => 'places#create', as: 'create_local'
 get'/places/edit/:id' => 'places#edit', as: 'edit_local'
 get'/places/destroy/:id' => 'places#destroy', as: 'destroy_local'
 get'/places/show/:id' => 'places#show', as: 'show_local'
 post'/places/update/:id' => 'places#update', as: 'update_local'

 #errors routes
 get '/notfound' => 'errors#404', as: 'notfound'

 #sessions routes
 post '/sessions/start' => 'sessions#start_session', as: 'start_session'
 get '/sessions/end' => 'sessions#end_session', as: 'end_session'

 #dashboard routes
 get '/dashboard' => 'dashboard#index', as: 'dashboard'

 #users routes
 get '/users' => 'users#index', as: 'users'
 get '/user/new' => 'users#new', as: 'new_user'
 get '/user/edit/:id' => 'users#edit', as: 'edit_user'
 get '/user/show/:id' => 'users#show', as: 'show_user'
 post '/user/create' => 'users#create', as: 'create_user'
 post '/user/update/:id' => 'users#update', as: 'update_user'
 get '/user/destroy/:id' => 'users#destroy', as: 'destroy_user'
 get '/user/profile/edit' => 'users#edit_profile', as: 'edit_profile_user'
 post '/user/profile/update' => 'users#update_profile', as: 'update_profile_user'
 get '/user/password/change' => 'users#change_password', as: 'change_password_user'
 post '/user/password/update' => 'users#update_password', as: 'update_password_user'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :end_date,
                  :name,
                  :size,
                  :start_date,
                  :local_id,
                  :function_user_projects_attributes,
                  :users_attributes,
                  :functions_attributes,
                  :releases_attributes,
                  :sprints_attributes,
                  :themes_attributes
                validates :name, presence: true
                validates :end_date, presence: true
                validates :start_date, presence: true
                validates :size, presence: true
                validates :local_id, presence: true

                  
  
  belongs_to :local
  has_many :function_user_projects, :dependent => :destroy
  has_many :users, through: :function_user_projects
  has_many :functions, through: :function_user_projects
  has_many :releases, :dependent => :destroy
  has_many :sprints, :dependent => :destroy
  has_many :themes, :dependent => :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
		@path_to_save = create_project_path
		
	end

	def show
		@project = Project.find(params[:id])
	end
	
	def edit
		@project = Project.find(params[:id])
		@path_to_save = update_project_path(params[:id])
		
	end

	def create
		@project = Project.new(params[:project])
		if @project.save
			redirect_to projects_path
		else
			@path_to_save = create_project_path
			render :new
		end

		
	end

	def update
		@project = Project.find(params[:id])
		if @project.update_attributes(params[:project])
			redirect_to projects_path
		else
			@path_to_save = update_project_path(params[:id])
			render :edit
			end
		
	end

	def destroy
		project = Project.find(params[:id])
		project.destroy
	rescue
	ensure
		redirect_to projects_path
		
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, url: @path_to_save, method: 'post' do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :start_date %>
	<%= f.text_field :start_date %>
	<%= f.label :end_date %>
	<%= f.text_field :end_date %>
	<%= f.label :size %>
	<%= f.text_field :size %>

	<%= f.collection_select :local_id, Local.all, :id, :country, prompt: true %>

	<%= f.submit 'Salvar'%>
<% end %>

app/views/projects/edit.html.erb
<h1>Editar Projeto</h1>
<hr>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projeto</h1>
<hr>
<%= link_to 'Novo', new_project_path %>
<table>
	<thead>
		<tr>
			<th>Nome</th>
			<th>Data inicial</th>
			<th>Data final</th>
			<th>Tamanho</th>
		</tr>
	</thead>
	<tbody>
		<% @projects.each do |project| %>
		<tr>
			<td><%= project.name%></td>
			<td><%= project.start_date%></td>
			<td><%= project.end_date%></td>
			<td><%= project.size%></td>
			<td>
				<%= link_to 'Editar', edit_project_path(project.id) %>
				<%= link_to 'Exibir', show_project_path(project.id) %>
				<%= link_to 'Excluir', destroy_project_path(project.id) %>
						
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/projects/new.html.erb
<h1>Novo projeto<h1>
<hr>
<%= render 'form' %>

app/views/projects/show.html.erb
<p>
	<h2> Nome: </h2>
	<%= @project.name %>
</p>
<p>
	<h2> Data de Início: </h2>
	<%= @project.start_date %>
</p>
<p>
	<h2> Date de Término:</h2> 
	<%= @project.end_date %>
</p>
<p>
	<h2> Tamanho total: </h2>
	<%= @project.size %>
</p>


<%= link_to 'Voltar', projects_path%> 